### ISSUE TITLE
兄弟 微信授权闪退了

### ISSUE THREAD

**Issue by flutterbest** [aichiko0225/flutter_umeng_ushare#1]

**Comment by minniexcode** [comment]
Android的吧，Android 的微信我暂时没申请到
主要原因是友盟 回调的result 是一个map，对象包含一个date对象，flutter不允许除开基础类型之外的类型

**Comment by minniexcode** [comment]
iOS的我昨天已经改了，Android 插件开发体验太差了，我要被恶心吐了

**Comment by flutterbest** [comment]
date那里是的 我也改过了

安卓的这样处理 

        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
        </provider>

**Comment by flutterbest** [comment]
我在他的基础上改的 https://github.com/youyiio/flutter_umeng_ushare ，可以看我fork的源码

**Comment by minniexcode** [comment]
这人代码全是错的，看个锤子
